Refactor api and update drawing logic
stevent-team/react-party pull request #8
Opened 2022-08-05 12:58 UTC by GRA0007

This is a large PR that will update the major version of this library. Changes the API to return `createConfetti` instead of `useConfetti` from the `useConfetti` hook, and an exported `Canvas` element that requires the user to pass in `canvasRef` from the hook as well.

Also updates the options used to control the confetti. Velocity uses a tuple, and many options have been simplified to use a min/max tuple. Also adds a `wind` option.

Improves the README with option tables.

Fixes #3

2022-08-05 14:18 UTC, giraugh requested changes
Thoughts
- I reckon `...props` instead of exporting a component.
- might be good if the api docs for wind and gravity mentioned that they were horizontal and vertical acceleration
- "range" rather than tuple?
- colors of type `string[]`
- shape functions of type `Record<string, function`
- shape weights of type `Record<string, number>`

2022-08-08 03:31 UTC, giraugh approved these changes
This is looking great `:D` - I left some thoughts and feedback but its up to you what you change. Also #teamtau

2022-08-08 03:31 UTC, giraugh commented on lib/config/index.js
> -export const TAU = Math.PI * 2
:angry:

2022-08-08 03:31 UTC, giraugh commented on lib/useConfetti.jsx
> +      transformMatrix.current = new DOMMatrix().scale(scale)
This *could* prob be a ReadOnlyDOMMatrix()

2022-08-08 03:31 UTC, giraugh commented on lib/useConfetti.jsx
> +        const [x, y] = [p.x - canvasBBoxRef.current.left, p.y - canvasBBoxRef.current.top]
I think using `const ctx =` helps with readability and also can be used to do the shorthand object syntax.

2022-08-08 03:31 UTC, giraugh commented on lib/useConfetti.jsx
> +        ctxRef.current.setTransform(transformMatrix.current.translate(x, y).rotate(p.angle).scale(1, Math.sin(((p.flip+90)*(Math.PI/180)))))
Prob worth folding these too for the reduced line length

2022-08-08 03:31 UTC, giraugh commented on lib/useConfetti.jsx
> +          flip: p.flip + (p.flipIncrement * (rotationVelocityCoefficient ? Math.min(Math.max(p.vy, p.vx), 2) * rotationVelocityCoefficient : 1) * speed),
I think extracting this line to a variable might also be worth it for readability sake. Like a `// compute rotation amount` block before we do the return

2022-08-08 03:31 UTC, giraugh commented on lib/util/index.js
> +  let rv = Math.random()
Might be pref to be `chooseWeighted(weights, randomValue=Math.random())`?

2022-08-08 03:31 UTC, giraugh commented on package.json
> -    "dev:sample": "vite dev",
Still not sold on this change hehe

2022-08-08 03:31 UTC, giraugh commented on sample/App.jsx
> +  const launch = useControls('Launch options', {
"Creation options" might be clearer

2022-08-08 03:31 UTC, giraugh commented on sample/App.jsx
> +  const confetti = useControls('Confetti options', {
"Movement options"?

2022-08-08 03:31 UTC, giraugh commented on sample/App.jsx
> +  const global = useControls('Global options', {
"Environment Options"?

2022-08-08 03:31 UTC, giraugh commented on sample/App.jsx
> +  const shapeWeights = useControls('Shape weights', {
It might be good to put the default shape weights in a config variable

2022-08-08 03:31 UTC, giraugh commented on sample/App.jsx
> +    loadImage("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 36 36'%3E%3Cpath fill='%23DD2E44' d='M35.885 11.833c0-5.45-4.418-9.868-9.867-9.868-3.308 0-6.227 1.633-8.018 4
Is it possible to load this from a seperate file? Or put it in a constant?

2022-08-08 03:57 UTC, GRA0007 commented on lib/config/index.js
> -export const TAU = Math.PI * 2
tau is dead, long live tau

2022-08-08 04:19 UTC, merged